// Namespace SpheresSheet Configuration Values
export const SpheresSheet = {};

/**
 * The set of Combat Spheres
 * @type {Object}
 */
SpheresSheet.combatSpheres = {
  alchemy: "SpheresSheet.SphereAlchemy",
  athletics: "SpheresSheet.SphereAthletics",
  barrage: "SpheresSheet.SphereBarrage",
  barroom: "SpheresSheet.SphereBarroom",
  beastmastery: "SpheresSheet.SphereBeastmastery",
  berserker: "SpheresSheet.SphereBerserker",
  boxing: "SpheresSheet.SphereBoxing",
  brute: "SpheresSheet.SphereBrute",
  dualWielding: "SpheresSheet.SphereDualWielding",
  duelist: "SpheresSheet.SphereDuelist",
  equipment: "SpheresSheet.SphereEquipment",
  fencing: "SpheresSheet.SphereFencing",
  gladiator: "SpheresSheet.SphereGladiator",
  guardian: "SpheresSheet.SphereGuardian",
  lancer: "SpheresSheet.SphereLancer",
  leadership: "SpheresSheet.SphereLeadership",
  openHand: "SpheresSheet.SphereOpenHand",
  scoundrel: "SpheresSheet.SphereScoundrel",
  scout: "SpheresSheet.SphereScout",
  shield: "SpheresSheet.SphereShield",
  sniper: "SpheresSheet.SphereSniper",
  tech: "SpheresSheet.SphereTech",
  trap: "SpheresSheet.SphereTrap",
  warleader: "SpheresSheet.SphereWarleader",
  wrestling: "SpheresSheet.SphereWrestling",
  alteration: "SpheresSheet.SphereAlteration",
  blood: "SpheresSheet.SphereBlood",
  conjuration: "SpheresSheet.SphereConjuration",
  creation: "SpheresSheet.SphereCreation",
  dark: "SpheresSheet.SphereDark",
  destruction: "SpheresSheet.SphereDestruction",
  divination: "SpheresSheet.SphereDivination",
  enhancement: "SpheresSheet.SphereEnhancement",
  fallenFey: "SpheresSheet.SphereFallenFey",
  fate: "SpheresSheet.SphereFate",
  illusion: "SpheresSheet.SphereIllusion",
  life: "SpheresSheet.SphereLife",
  light: "SpheresSheet.SphereLight",
  mana: "SpheresSheet.SphereMana",
  mind: "SpheresSheet.SphereMind",
  nature: "SpheresSheet.SphereNature",
  protection: "SpheresSheet.SphereProtection",
  telekinesis: "SpheresSheet.SphereTelekinesis",
  time: "SpheresSheet.SphereTime",
  war: "SpheresSheet.SphereWar",
  warp: "SpheresSheet.SphereWarp",
  weather: "SpheresSheet.SphereWeather",
  bear: "SpheresSheet.SphereBear",
  technomancy: "SpheresSheet.SphereTechnomancy",
  veilweaving: "SpheresSheet.SphereVeilweaving",
}